#!/usr/bin/env python3

import sys
import os

# Add the sidebyside directory to Python path
sys.path.insert(0, '/Users/michaelbernaski/Documents/sidebyside')

# Import and run the config script
from config import create_config

if __name__ == "__main__":
    create_config()